### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by mattkaye** [jakobsen/fluid-typography#9] opened 2021-05-27 15:45 UTC
The fix for this is to apply min-height: 0vw; to the text you want to apply the clamp to. Maybe this can added to the example site? Very useful too. Thanks!

Safari Version 14.0.3

**Comment by jakobsen** [comment] 2021-05-30 10:07
Hm, it's working as expected for me in the same version of Safari. The text has a `min-height: 0vh` rule applied to it, which is essentially the same fix. Could you post a gif or something similar demonstrating the issue?

Sorry for the late reply! :)

<img width="1021" alt="Skjermbilde 2021-05-30 kl  12 07 28" src="https://user-images.githubusercontent.com/16143117/120100196-a62d0200-c13f-11eb-88eb-1771ccd5e801.png">

**Comment by jakobsen** [comment] 2021-06-05 09:26
I'm closing this for now as it seems to be working as intended. Feel free to re-open if necessary.

**Closed as completed by jakobsen** 2021-06-05 09:26 UTC
